find_path(ASIO_UDP_DEVICE_INCLUDE_DIR asio_udp_device/ASIOUDPDevice.h
  PATHS "${CMAKE_CURRENT_LIST_DIR}/../include"
  PATH_SUFFIXES asio_udp_device)
set(ASIO_UDP_DEVICE_INCLUDE_DIRS ${ASIO_UDP_DEVICE_INCLUDE_DIR})

find_library(ASIO_UDP_DEVICE_LIBRARY NAMES asio_udp_device
  PATHS "${CMAKE_CURRENT_LIST_DIR}/../lib")
set(ASIO_UDP_DEVICE_LIBRARIES ${ASIO_UDP_DEVICE_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(ASIO_UDP_DEVICE
  DEFAULT_MSG
  ASIO_UDP_DEVICE_LIBRARY
  ASIO_UDP_DEVICE_INCLUDE_DIR)

mark_as_advanced(ASIO_UDP_DEVICE_INCLUDE_DIR ASIO_UDP_DEVICE_LIBRARY)
